controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# config/routes.yaml
login_custom:
    path: /api/login_custom # CAMBAIR EL NOMBRE DE LA RUTA Q ES MU FEO
    controller: App\Controller\HomeController::token

 #######################
# CRUD -> Entity User #
#######################

# Show user list
user_list:
    path: api/user/list
    controller: App\Controller\UserRegisterController::show

# Read playerById
app_user_list_id:
    path: api/user/api/user/showUId
    controller: App\Controller\UserController::api/user/showUId


# Read playerById
app_user_list_criteria:
    path: api/user/criteria
    controller: App\Controller\UserController::criteria

 ########################
# CRUD -> Entity League #
########################

# Create league
app_league_create:
    path: api/league/create
    controller: App\Controller\LeagueController::create

# Read league
app_league_read:
    path: api/league/read
    controller: App\Controller\LeagueController::read

# Read league
app_league_state:
    path: api/league/state
    controller: App\Controller\LeagueController::state

 #######################
# CRUD -> Entity Round #
#######################

# Create round
app_round_create:
    path: api/round/create
    controller: App\Controller\RoundController::create


# Read round
#app_round_read:
#    path: api/round/create
#    controller: App\Controller\RoundController::read


 ########################
# CRUD -> Entity Player #
########################

# Player register
app_player_register:
    path: api/player/register
    controller: App\Controller\PlayerController::register


# Read player
app_player_list:
    path: api/player/showPJ
    controller: App\Controller\PlayerController::showPJ

# Read playerById
app_player_list_id:
    path: api/player/showPJId
    controller: App\Controller\PlayerController::showPJId


# Read playerById
app_player_list_criteria:
    path: api/player/criteria
    controller: App\Controller\PlayerController::criteria





