controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# config/routes.yaml
login_custom:
    path: /api/login_custom
    controller: App\Controller\HomeController::token



# Delete user
#delete_user:
#    path: /user/{id}
#    controller: App\Controller\UserRegisterController::delete