controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# config/routes.yaml
login_custom:
    path: /api/login_custom
    controller: App\Controller\HomeController::token

# Player register
app_player_register:
    path: api/player/register
    controller: App\Controller\PlayerRegisterController

# Show user list
user_list:
    path: api/user/list
    controller: App\Controller\UserRegisterController::show

# Create leagyue
app_league_create:
    path: api/league/create
    controller: App\Controller\LeagueGeneratorController::create





# Delete user
#delete_user:
#    path: /user/{id}
#    controller: App\Controller\UserRegisterController::delete