controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# config/routes.yaml
login_custom:
    path: /api/login_custom # CAMBAIR EL NOMBRE DE LA RUTA Q ES MU FEO
    controller: App\Controller\HomeController::token

 #######################
# CRUD -> Entity User #
#######################

# Show user list
user_list:
    path: api/user/list
    controller: App\Controller\UserController::list

# Show user list
user_create:
    path: api/user/create
    controller: App\Controller\UserController::create

# Show user profile
user_profile:
    path: api/user/profile
    controller: App\Controller\UserController::userId

# Read user by Id
app_user_list_id:
    path: api/user/api/user/showUId
    controller: App\Controller\UserController::api/user/showUId


# Read user by criteria
app_user_list_criteria:
    path: api/user/criteria
    controller: App\Controller\UserController::criteria

# Edit user
edit_user:
    path: /api/user/{id}
    controller: App\Controller\UserController::editById

# Edit my user
edit_my_user:
    path: /api/user
    controller: App\Controller\UserController::edit

 ########################
# CRUD -> Entity League #
########################

# Create league
app_league_create:
    path: api/league/create
    controller: App\Controller\LeagueController::create

# Read league
app_league_read:
    path: api/league/read
    controller: App\Controller\LeagueController::read

# Read 'Initial state' league
app_league_init_league:
    path: api/league/view/init/league
    controller: App\Controller\LeagueController::viewInitLeague

# Read open league
app_league_open_league:
    path: api/league/view/open/league
    controller: App\Controller\LeagueController::viewOpenLeague

# Read state league
app_league_state:
    path: api/league/state
    controller: App\Controller\LeagueController::state

# Read state league
app_league_enroll:
    path: api/league/enroll/{id}
    controller: App\Controller\LeagueController::enroll

# Edit league
app_league_edit_league:
    path: api/league/view/edit/league/{id}
    controller: App\Controller\LeagueController::editLeague


 #######################
# CRUD -> Entity Round #
#######################

# Read rounds&games created
app_show_create_rounds_games:
    path: api/show/create/rounds&games
    controller: App\Controller\RoundController::showRoundNDGames

# Read myleagues
app_league_participate:
    path: api/show/my/leagues
    controller: App\Controller\RoundController::showMe

# Read participants in league
app_league_participants:
    path: api/round/show/players/leagues
    controller: App\Controller\RoundController::show

# Create round
app_league_round_create:
    path: api/league/round/create/{id}
    controller: App\Controller\RoundController::create

# Read round
app_edit_status-game:
    path: api/edit/status-game/{id}
    controller: App\Controller\RoundController::editStatus

# Read leagues-players
app_show_leagues_player:
    path: api/show/league-players
    controller: App\Controller\RoundController::showRelation



